version: '2.1'
services:
  jenkins:
    image: "jenkins/jenkins"
    user: root
    environment:
      JAVA_OPTS: "-Djava.awt.headless=true"
    ports:
      - "50000:50000"
      - "8880:8080"
    volumes: 
      - jenkins_volume:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker

volumes:
  jenkins_volume:
    driver: local
