spring:
  profiles:
    active: test
  devtools:
    restart:
      enabled: true
swagger:
  production: false
  basic:
    enable: false
    username: jeecg
    password: jeecg1314
system:
  #注册用户默认密码
  defaultPwd: 123456
  #注册用户默认角色ID
  defaultRoleId: 100
  #注册用户默认组织机构ID
  defaultOrgId: 0
  #不需要数据权限过滤的角色key
  noDataFilterRole: DATA_NO_FILTER
  #用户每日收取短信上限
  smsTimes: 25
  #不同终端用户的超时时间（web用户3小时，app，微信，小程序时间自己定半年或永久）Long型，后面记得加l
  expireTime: "{web: 10800000l, app: 15768000000l}"
restTemplate:
  #连接池的最大连接数默认为0
  maxTotalConnect: 0
  #单个主机的最大连接数
  maxConnectPerRoute: 200
  #连接超时默认2s
  connectTimeout: 2000
  #读取超时默认30s
  readTimeout: 30000