spring:
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
swagger:
  production: false
  basic:
    enable: true
    username: jeecg
    password: jeecg1314
